config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#main'

  get 'pages/reviews'
  post 'pages/reviews', to: 'pages#new_review'
  delete 'pages/destroy/:id', to: 'pages#destroy', as: 'destroy_review'
  get 'profile/update', to: 'profile#update'
  post 'profile/update', to: 'profile#edit'
  get 'unit/index', to: 'unit#index'
  get 'unit/new', to: 'unit#new'
  post 'unit/new', to: 'unit#create'
  get 'unit/show/:id', to: 'unit#show', as: 'unit_show'
  get 'unit/edit/:id', to: 'unit#edit', as: 'unit_edit'
  post 'unit/edit/:id', to: 'unit#update'
  delete 'unit/destroy/:id', to: 'unit#destroy', as: 'unit_destroy'
  get 'contacts/', to: 'pages#contacts'
  get 'teachers/', to: 'pages#teachers'
  get 'story/', to: 'pages#story'
  get 'administration/', to: 'pages#administration'
  get 'news/', to: 'pages#news'
  post 'contacts/', to: 'pages#contacts_send'
  get 'questions', to: 'pages#questions'
  delete 'questions/destroy/:id', to: 'pages#destroy_question', as: 'destroy_question'
  get 'answers', to: 'answer#index'

  post 'answers', to: 'answer#create', as: 'create_answer'
  get 'services/', to: 'service#index'
  get 'services/new', to: 'service#new'
  delete 'services/destroy/:id', to: 'service#destroy', as: 'destroy_service'
  post 'services/new', to: 'service#create'
  post 'services/edit/:id', to: 'service#update', as: 'update_service'
  get 'services/edit/:id', to: 'service#edit', as: 'edit_service'


  get 'workers/', to: 'workers#index'
  get 'workers/new', to: 'workers#new'
  delete 'workers/destroy/:id', to: 'workers#destroy', as: 'destroy_worker'
  post 'workers/new', to: 'workers#create'
  post 'workers/edit/:id', to: 'workers#update', as: 'update_worker'
  get 'workers/edit/:id', to: 'workers#edit', as: 'edit_worker'
  get 'about/', to: 'pages#about_us'
  get 'reviews/moderation', to: 'pages#reviews_moderation'
  post 'reviews/moderation', to: 'pages#reviews_moderation_send'
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true, length: { minimum: 5 ,maximum: 25 }
  validates :description, presence: true, length: { minimum: 5 ,maximum: 100 }
  validates :big_desc, presence: true, length: { minimum: 30 ,maximum: 10000 }
  validates :address, presence: true, length: { minimum: 3 ,maximum: 50 }
  validates :leader, presence: true, length: { minimum: 3 ,maximum: 50 }
  phoneRegex= /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/
  validates :leader_phone, presence: true, length: { minimum: 10 ,maximum: 14 }, format: { with: phoneRegex }
  validates :legal_phone, presence: true, length: { minimum: 10 ,maximum: 14 }, format: { with: phoneRegex }
end

app/controllers/unit_controller.rb
class UnitController < ApplicationController
  before_action :require_signed_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  def index
    @units = Unit.paginate(page: params[:page], per_page: 9)
  end
  def new
    @unit = Unit.new
  end
  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      flash[:notice] = "Отделение успешно создано"
      redirect_to unit_index_path
    else
      flash[:alert] = "Отделение не создано"
      render 'new'
    end
  end
  def show
    @unit = Unit.find(params[:id])
  end
  def edit
    @unit = Unit.find(params[:id])
  end
  def update
    @unit = Unit.find(params[:id])
    if @unit.update(unit_params)
      flash[:notice] = "Отделение успешно изменено"
      redirect_to unit_index_path
    else
      flash[:alert] = "Отделение не изменено"
      render 'edit'
    end
  end
  def destroy
    @unit = Unit.find(params[:id])
    if @unit.destroy
      flash[:notice] = "Отделение успешно удалено"
      redirect_to unit_index_path
    else
      flash[:alert] = "Отделение не удалено"
      render 'index'
    end
  end

  private
    def unit_params
      params.require(:unit).permit(:name, :description, :image, :big_desc, :address, :leader, :legal_phone, :leader_phone)
    end

  def require_signed_user
    unless current_user
      flash[:alert] = "Вы должны войти в систему"
      redirect_to root_path
    end
  end
  def require_admin
    unless current_user.admin?
      flash[:alert] = "Вы должны быть администратором"
      redirect_to root_path
    end
  end

end

app/helpers/unit_helper.rb
module UnitHelper
end

app/views/unit/edit.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular sticky address card outline inverted  icon"></i>
  Редактировать отделение
</h2>

<%= form_for :unit do |f|  %>

  <div class="ui segment inverted">
    <%=render 'devise/shared/error_messages', resource: @unit %>
    <div class="ui form inverted">
      <div class="avatar">
        <% if @unit.image.attached? %>
          <%=image_tag(@unit.image, class: 'avatar')%>
        <% else %>
          <%= image_tag('unit-default.png', class: 'avatar') %>
        <% end %>
      </div>
      <div class="field">
        <%=f.label 'Картинка' %>
        <%=f.file_field :image %>
      </div>
      <div class="field">
        <%= f.label 'Название'  %>
        <%= f.text_field :name, placeholder: 'Название' %>
      </div>
      <div class="field">
        <%= f.label 'Краткое описание' %>
        <%= f.text_field :description, placeholder: 'Краткое описание' %>
      </div>
      <div class="field">
        <%= f.label 'Местоположение отделения'  %>
        <%= f.text_field :address, placeholder: 'Местоположение отделения' %>
      </div>
      <div class="field">
        <%= f.label 'Имя заведующего' %>
        <%= f.text_field :leader, placeholder: 'Имя заведующего' %>
      </div>
      <div class="field">
        <%= f.label 'Телефон заведующего' %>
        <%= f.text_field :leader_phone, placeholder: 'Телефон заведующего' %>
      </div>
      <div class="field">
        <%= f.label 'Телефон юридического отдела'%>
        <%= f.text_field :legal_phone, placeholder: 'Телефон юридического отдела' %>
      </div>
      <div class="field">
        <%= f.label 'Полное описание' %>
        <%= f.text_area :big_desc, placeholder: 'Полное описание' %>
      </div>
      <%= f.submit "Добавить", class: 'ui button'%>
    </div>
  </div>
<% end %>

app/views/unit/show.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular sticky building outline inverted outline icon"></i>
 <%= @unit.name %>
<div>
  <% if current_user && current_user.admin? %>
    <%= link_to 'Изменить', unit_edit_path(@unit), class: 'ui orange button' %>
    <%= link_to 'Удалить', unit_destroy_path(@unit), class: 'ui red button', method: :delete %>
  <% end %>
</div>
</h2>
<div class="unit-show-content">

  <% if @unit.image.attached? %>
    <%=image_tag(@unit.image, class: 'unit-show-image')%>
  <% else %>
    <%= image_tag('unit-default.png', class: 'unit-show-image') %>
  <% end %>
  <div class="unit-data-handler">
    <ul>
      <li>Юридический адрес: <%=@unit.address %></li>
      <li>Глава отделения: <%=@unit.leader %></li>
      <li>Номер главы отделения: <%=@unit.leader_phone %></li>
      <li>Номер юридического отдела: <%=@unit.legal_phone %></li>
    </ul>
  </div>
</div>
<div class="unit-show-content">
  <h1>Подробное описание отделения</h1>
</div>

<div class="description-unit-show">
  <p class="unit-full-description"><%=@unit.big_desc %></p>
</div>