config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#main'

  get 'pages/reviews'
  post 'pages/reviews', to: 'pages#new_review'
  delete 'pages/destroy/:id', to: 'pages#destroy', as: 'destroy_review'
  get 'profile/update', to: 'profile#update'
  post 'profile/update', to: 'profile#edit'
  get 'unit/index', to: 'unit#index'
  get 'unit/new', to: 'unit#new'
  post 'unit/new', to: 'unit#create'
  get 'unit/show/:id', to: 'unit#show', as: 'unit_show'
  get 'unit/edit/:id', to: 'unit#edit', as: 'unit_edit'
  post 'unit/edit/:id', to: 'unit#update'
  delete 'unit/destroy/:id', to: 'unit#destroy', as: 'unit_destroy'
  get 'contacts/', to: 'pages#contacts'
  get 'teachers/', to: 'pages#teachers'
  get 'story/', to: 'pages#story'
  get 'administration/', to: 'pages#administration'
  get 'news/', to: 'pages#news'
  post 'contacts/', to: 'pages#contacts_send'
  get 'questions', to: 'pages#questions'
  delete 'questions/destroy/:id', to: 'pages#destroy_question', as: 'destroy_question'
  get 'answers', to: 'answer#index'

  post 'answers', to: 'answer#create', as: 'create_answer'
  get 'services/', to: 'service#index'
  get 'services/new', to: 'service#new'
  delete 'services/destroy/:id', to: 'service#destroy', as: 'destroy_service'
  post 'services/new', to: 'service#create'
  post 'services/edit/:id', to: 'service#update', as: 'update_service'
  get 'services/edit/:id', to: 'service#edit', as: 'edit_service'


  get 'workers/', to: 'workers#index'
  get 'workers/new', to: 'workers#new'
  delete 'workers/destroy/:id', to: 'workers#destroy', as: 'destroy_worker'
  post 'workers/new', to: 'workers#create'
  post 'workers/edit/:id', to: 'workers#update', as: 'update_worker'
  get 'workers/edit/:id', to: 'workers#edit', as: 'edit_worker'
  get 'about/', to: 'pages#about_us'
  get 'reviews/moderation', to: 'pages#reviews_moderation'
  post 'reviews/moderation', to: 'pages#reviews_moderation_send'
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true, length: { minimum: 3,maximum: 50 }
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: email_regex } , uniqueness: true
  validates :position, presence: true, length: { minimum: 3,maximum: 20 }
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :require_user, only: [  :new, :create, :edit, :update, :destroy]
  before_action :need_admin, only: [  :new, :create, :edit, :update, :destroy]

  def index
    @workers = Worker.paginate(:page => params[:page], :per_page => 9)
  end

  def destroy
    worker = Worker.find(params[:id])
    if worker.destroy
      flash[:notice] = "Сотрудник успешно удален"
      redirect_to workers_path
    else
      flash[:alert] = "Ошибка удаления сотрудника"
      render 'index'
    end
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    @worker.image=params[:worker]["Загрузить фото"] if params[:worker]["Загрузить фото"]
    if @worker.save
      flash[:notice] = "Сотрудник успешно создана"
      redirect_to workers_path
    else
      flash[:alert] = "Сотрудник создания услуги"
      render 'new'
    end
  end

  def update
    @worker = Worker.find(params[:id])
    @worker.image=params[:worker]["Загрузить фото"] if params[:worker]["Загрузить фото"]
    if @worker.update_attributes(worker_params)
      flash[:notice] = "Сотрудник успешно обновлен"
      redirect_to workers_path
    else
      flash[:alert] = "Ошибка обновления сотрудника"
      render 'edit'
    end
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  private
  def worker_params
    params.require(:worker).permit(:name, :email, :position, :image)
  end

  def require_user
    unless user_signed_in?
      flash[:alert] = "Для доступа к этой странице необходимо авторизоваться"
      redirect_to new_user_session_path
    end
  end

  def need_admin
    unless  current_user.is_admin?
      flash[:alert] = "Для доступа к этой странице необходимо быть администратором"
      redirect_to root_path
    end
  end

end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/edit.html.erb
<h2 class="ui center aligned icon header">
  <div class="top-slogan-handler">
    <%= image_tag('workers.png', class: 'top-slogan-image') %>
    <h1 class="slogan" style="margin-left: 15px">Редактировать сотрудника</h1>
  </div>
</h2>
<div class="center-my ">
  <%= form_for :worker do |f|  %>

    <div class="ui segment profile ">
      <%=render 'devise/shared/error_messages', resource: @worker %>

      <div class="ui form ">
        <div class="avatar-handler">
          <%= image_tag('pim.png', class: 'avatar-serv') %>
        </div>
        <div class="field">
          <%=f.label 'Загрузить фото', class:'ui secondary button pick-image-button' %>
          <label for="">
          <span style="display: none">
             <%=f.file_field 'Загрузить фото'%>
          </span>
          </label>
        </div>
        <div class="field">
          <%= f.label 'ФИО сотрудника' %>
          <%= f.text_field :name, placeholder: 'ФИО сотрудника', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Почта" %>
          <%= f.text_field :email, placeholder: 'Почта', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Должность" %>
          <%= f.text_field :position, placeholder: 'Стоимость', class:'data-input'  %>
        </div>
        <%= f.submit "Редактировать", class: 'ui button secondary'%>
      </div>
    </div>
  <% end %>
</div>

app/views/workers/index.html.erb
<h2 class="ui center aligned icon header">
  <div class="top-slogan-handler">
    <%= image_tag('workers.png', class: 'top-slogan-image') %>
    <h1 class="slogan" style="margin-left: 15px">Список работников</h1>
  </div>
  <% if current_user && current_user.admin? %>
    <div style="margin-top: 10px">
      <%= link_to 'Добавить нового сотрудника', workers_new_path, class: 'ui green button' %>
    </div>
  <% end %>
</h2>


<div class="services">
  <% @workers.each do |u| %>

    <div class="unit-solo-handler">
      <div class="ui card">
        <div class="image">
          <% if u.image.attached? %>
            <%= image_tag(u.image, class: 'unit-image') %>
          <% else %>
            <%= image_tag('pim.png', class: 'unit-image') %>
          <% end %>
        </div>
        <div class="content unit-desc-handler">
          <a class="header"><%= u.name %></a>
          <div class="meta">
            <span class="date"><%= u.position %></span>
          </div>
          <div class="unit-description">
            <%= u.email %>
          </div>
        </div>

        <% if current_user && current_user.admin? %>
          <div class="extra content">
            <%= link_to 'Изменить', edit_worker_path(u), class: 'ui secondary button' %>
            <%= link_to 'Удалить', destroy_worker_path(u), class: 'ui secondary button', style: 'margin-top:10px', method: :delete %>
          </div>
        <% end %>

      </div>


    </div>


  <% end %>
</div>

<div class="unit-show-content">
  <%= will_paginate @workers %>
</div>

app/views/workers/new.html.erb
<h2 class="ui center aligned icon header">
  <div class="top-slogan-handler">
    <%= image_tag('workers.png', class: 'top-slogan-image') %>
    <h1 class="slogan" style="margin-left: 15px">Создание нового сотрудника</h1>
  </div>
</h2>
<div class="center-my ">
  <%= form_for :worker do |f|  %>

    <div class="ui segment profile ">
      <%=render 'devise/shared/error_messages', resource: @worker %>

      <div class="ui form ">
        <div class="avatar-handler">
          <%= image_tag('pim.png', class: 'avatar-serv') %>
        </div>
        <div class="field">
          <%=f.label 'Загрузить фото', class:'ui secondary button pick-image-button' %>
          <label for="">
          <span style="display: none">
             <%=f.file_field 'Загрузить фото'%>
          </span>
          </label>
        </div>
        <div class="field">
          <%= f.label 'ФИО сотрудника' %>
          <%= f.text_field :name, placeholder: 'ФИО сотрудника', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Почта" %>
          <%= f.text_field :email, placeholder: 'Почта', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Должность" %>
          <%= f.text_field :position, placeholder: 'Стоимость', class:'data-input'  %>
        </div>
        <%= f.submit "Создать", class: 'ui button secondary'%>
      </div>
    </div>
  <% end %>
</div>