config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#main'

  get 'pages/reviews'
  post 'pages/reviews', to: 'pages#new_review'
  delete 'pages/destroy/:id', to: 'pages#destroy', as: 'destroy_review'
  get 'profile/update', to: 'profile#update'
  post 'profile/update', to: 'profile#edit'
  get 'unit/index', to: 'unit#index'
  get 'unit/new', to: 'unit#new'
  post 'unit/new', to: 'unit#create'
  get 'unit/show/:id', to: 'unit#show', as: 'unit_show'
  get 'unit/edit/:id', to: 'unit#edit', as: 'unit_edit'
  post 'unit/edit/:id', to: 'unit#update'
  delete 'unit/destroy/:id', to: 'unit#destroy', as: 'unit_destroy'
  get 'contacts/', to: 'pages#contacts'
  get 'teachers/', to: 'pages#teachers'
  get 'story/', to: 'pages#story'
  get 'administration/', to: 'pages#administration'
  get 'news/', to: 'pages#news'
  post 'contacts/', to: 'pages#contacts_send'
  get 'questions', to: 'pages#questions'
  delete 'questions/destroy/:id', to: 'pages#destroy_question', as: 'destroy_question'
  get 'answers', to: 'answer#index'

  post 'answers', to: 'answer#create', as: 'create_answer'
  get 'services/', to: 'service#index'
  get 'services/new', to: 'service#new'
  delete 'services/destroy/:id', to: 'service#destroy', as: 'destroy_service'
  post 'services/new', to: 'service#create'
  post 'services/edit/:id', to: 'service#update', as: 'update_service'
  get 'services/edit/:id', to: 'service#edit', as: 'edit_service'


  get 'workers/', to: 'workers#index'
  get 'workers/new', to: 'workers#new'
  delete 'workers/destroy/:id', to: 'workers#destroy', as: 'destroy_worker'
  post 'workers/new', to: 'workers#create'
  post 'workers/edit/:id', to: 'workers#update', as: 'update_worker'
  get 'workers/edit/:id', to: 'workers#edit', as: 'edit_worker'
  get 'about/', to: 'pages#about_us'
  get 'reviews/moderation', to: 'pages#reviews_moderation'
  post 'reviews/moderation', to: 'pages#reviews_moderation_send'
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true, length: { minimum: 15, maximum: 25 }
  validates :description, presence: true, length: { minimum: 15, maximum: 250 }
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  before_action :require_user, only: [  :new, :create, :edit, :update, :destroy]
  before_action :need_admin, only: [  :new, :create, :edit, :update, :destroy]

  def index
    @services = Service.paginate(:page => params[:page], :per_page => 9)
  end

  def new
    @service = Service.new
  end

  def destroy
    service = Service.find(params[:id])
    if service.destroy
      flash[:notice] = "Услуга успешно удалена"
      redirect_to services_path
    else
      flash[:alert] = "Ошибка удаления услуги"
      render 'index'
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @service.image=params[:service]["Загрузить фото"] if params[:service]["Загрузить фото"]
    if @service.update_attributes(service_params)
      flash[:notice] = "Услуга успешно обновлена"
      redirect_to services_path
    else
      flash[:alert] = "Ошибка обновления услуги"
      render 'edit'
    end
  end

  def create
    @service = Service.new(service_params)
    @service.image=params[:service]["Загрузить фото"] if params[:service]["Загрузить фото"]
    if @service.save
      flash[:notice] = "Услуга успешно создана"
      redirect_to services_path
    else
      flash[:alert] = "Ошибка создания услуги"
      render 'new'
    end
  end
  private
  def service_params
    params.require(:service).permit(:name, :description, :price, :image)
  end
  def require_user
    unless user_signed_in?
      flash[:alert] = "Для доступа к этой странице необходимо авторизоваться"
      redirect_to new_user_session_path
    end
  end

  def need_admin
    unless  current_user.is_admin?
      flash[:alert] = "Для доступа к этой странице необходимо быть администратором"
      redirect_to root_path
    end
  end

end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/service/edit.html.erb
<h2 class="ui center aligned icon header">
  <div class="top-slogan-handler">
    <%= image_tag('serv.png', class: 'top-slogan-image') %>
    <h1 class="slogan" style="margin-left: 15px">Редактирование услуги</h1>
  </div>
</h2>

<div class="center-my ">
  <%= form_for :service do |f|  %>

    <div class="ui segment profile ">
      <%=render 'devise/shared/error_messages', resource: @service %>

      <div class="ui form ">
        <div class="avatar-handler">
          <% if @service.image.attached? %>
            <%= image_tag(@service.image, class: 'exist-avatar-serv') %>
          <% else %>
            <%= image_tag('unit-default.png', class: 'avatar') %>
          <% end %>
        </div>
        <div class="field">
          <%=f.label 'Загрузить фото', class:'ui secondary button pick-image-button' %>
          <label for="">
          <span style="display: none">
             <%=f.file_field 'Загрузить фото'%>
          </span>
          </label>
        </div>
        <div class="field">
          <%= f.label 'Название' %>
          <%= f.text_field :name, placeholder: 'Название', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Описание" %>
          <%= f.text_field :description, placeholder: 'Описание', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Стоимость" %>
          <%= f.text_field :price, placeholder: 'Стоимость', class:'data-input'  %>
        </div>
        <%= f.submit "Создать
", class: 'ui button secondary'%>
      </div>
    </div>
  <% end %>
</div>

app/views/service/index.html.erb
<h2 class="ui center aligned icon header">
<div class="top-slogan-handler">
  <%= image_tag('serv.png', class: 'top-slogan-image') %>
  <h1 class="slogan" style="margin-left: 15px">Список услуг</h1>
</div>
<% if current_user && current_user.admin? %>
  <div style="margin-top: 10px">
    <%= link_to 'Добавить новую услугу', services_new_path, class: 'ui green button' %>
  </div>
<% end %>
</h2>


<div class="services">
  <% @services.each do |u| %>

    <div class="unit-solo-handler">
      <div class="ui card">
        <div class="image">
          <% if u.image.attached? %>
            <%= image_tag(u.image, class: 'unit-image') %>
          <% else %>
            <%= image_tag('ser.png', class: 'unit-image') %>
          <% end %>
        </div>
        <div class="content unit-desc-handler">
          <a class="header"><%= u.name %></a>
          <div class="meta">
            <span class="date"><%= u.created_at.strftime("Created %m/%d/%Y at %I:%M%p") %></span>
          </div>
          <div class="unit-description">
            <%= u.description %>
          </div>
        </div>

          <% if current_user && current_user.admin? %>
          <div class="extra content">
            <%= link_to 'Изменить', edit_service_path(u), class: 'ui secondary button' %>
            <%= link_to 'Удалить', destroy_service_path(u), class: 'ui secondary button', style: 'margin-top:10px', method: :delete %>
          </div>
          <% end %>

      </div>


    </div>


  <% end %>
</div>

<div class="unit-show-content">
  <%= will_paginate @services %>
</div>

app/views/service/new.html.erb
<h2 class="ui center aligned icon header">
  <div class="top-slogan-handler">
    <%= image_tag('serv.png', class: 'top-slogan-image') %>
    <h1 class="slogan" style="margin-left: 15px">Создание новой услуги</h1>
  </div>
</h2>
<div class="center-my ">
  <%= form_for :service do |f|  %>

    <div class="ui segment profile ">
      <%=render 'devise/shared/error_messages', resource: @service %>

      <div class="ui form ">
        <div class="avatar-handler">
            <%= image_tag('ser.png', class: 'avatar-serv') %>
        </div>
        <div class="field">
          <%=f.label 'Загрузить фото', class:'ui secondary button pick-image-button' %>
          <label for="">
          <span style="display: none">
             <%=f.file_field 'Загрузить фото'%>
          </span>
          </label>
        </div>
        <div class="field">
          <%= f.label 'Название' %>
          <%= f.text_field :name, placeholder: 'Название', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Описание" %>
          <%= f.text_field :description, placeholder: 'Описание', class:'data-input'  %>
        </div>
        <div class="field">
          <%= f.label "Стоимость" %>
          <%= f.text_field :price, placeholder: 'Стоимость', class:'data-input'  %>
        </div>
        <%= f.submit "Создать
", class: 'ui button secondary'%>
      </div>
    </div>
  <% end %>
</div>