config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#main'

  get 'pages/reviews'
  post 'pages/reviews', to: 'pages#new_review'
  delete 'pages/destroy/:id', to: 'pages#destroy', as: 'destroy_review'
  get 'profile/update', to: 'profile#update'
  post 'profile/update', to: 'profile#edit'
  get 'unit/index', to: 'unit#index'
  get 'unit/new', to: 'unit#new'
  post 'unit/new', to: 'unit#create'
  get 'unit/show/:id', to: 'unit#show', as: 'unit_show'
  get 'unit/edit/:id', to: 'unit#edit', as: 'unit_edit'
  post 'unit/edit/:id', to: 'unit#update'
  delete 'unit/destroy/:id', to: 'unit#destroy', as: 'unit_destroy'
  get 'contacts/', to: 'pages#contacts'
  get 'teachers/', to: 'pages#teachers'
  get 'story/', to: 'pages#story'
  get 'administration/', to: 'pages#administration'
  get 'news/', to: 'pages#news'
  post 'contacts/', to: 'pages#contacts_send'
  get 'questions', to: 'pages#questions'
  delete 'questions/destroy/:id', to: 'pages#destroy_question', as: 'destroy_question'
  get 'answers', to: 'answer#index'

  post 'answers', to: 'answer#create', as: 'create_answer'
  get 'services/', to: 'service#index'
  get 'services/new', to: 'service#new'
  delete 'services/destroy/:id', to: 'service#destroy', as: 'destroy_service'
  post 'services/new', to: 'service#create'
  post 'services/edit/:id', to: 'service#update', as: 'update_service'
  get 'services/edit/:id', to: 'service#edit', as: 'edit_service'


  get 'workers/', to: 'workers#index'
  get 'workers/new', to: 'workers#new'
  delete 'workers/destroy/:id', to: 'workers#destroy', as: 'destroy_worker'
  post 'workers/new', to: 'workers#create'
  post 'workers/edit/:id', to: 'workers#update', as: 'update_worker'
  get 'workers/edit/:id', to: 'workers#edit', as: 'edit_worker'
  get 'about/', to: 'pages#about_us'
  get 'reviews/moderation', to: 'pages#reviews_moderation'
  post 'reviews/moderation', to: 'pages#reviews_moderation_send'
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="ui success message">
    <i class="close icon"></i>
    <div class="header">
      <%= notice %>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="ui negative message">
    <i class="close icon"></i>
    <div class="header">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="site-footer">
    <div class="footer-data">
      <p class="copyright-text">Copyright &copy; 2022 All Rights Reserved by Дима Красиков
      <div class="logo-container">
        <a href="https://web.telegram.org/k/"><%=image_tag('whatsapp.png', class:'viber-logo') %></a>
        <a href="https://web.telegram.org/k/"><%=image_tag('telega.png', class:'viber-logo') %></a>
        <a href="https://web.telegram.org/k/"><%=image_tag('viber.png', class:'viber-logo') %></a>



      </div>
    </div>
    <hr>

  </footer>

app/views/layouts/_nav.html.erb
<div class="ui mini menu massive ">
  <a class="item" href="/">

    <%=image_tag('logot.png', class:'my-logo-img') %>
  </a>

  <%= link_to 'Контакты', contacts_path, class: 'item' %>





  <%= link_to "Услуги", services_path, class: 'item' %>
  <%= link_to "Работники", workers_path, class: 'item' %>
  <%= link_to 'Отзывы', pages_reviews_path, class: 'item' %>
  <%= link_to 'О нас', about_path, class: 'item' %>

  <% if user_signed_in? %>
    <%= link_to "Ваши вопросы", questions_path, class: 'item' %>

    <% if current_user.is_admin? %>
      <div class="right menu">
        <div class="ui dropdown item" style="color: red">
          Админ панель
          <div class="menu">
            <%= link_to "Вопросы", answers_path, class: 'item' %>
            <%= link_to "Модерация отзывов",  reviews_moderation_path, class: "item" %>
            <%= link_to "Модерация списка услуг", services_path, class: "item" %>
            <%= link_to "Модерация списка работников", workers_path, class: "item" %>
          </div>
        </div>

    <% end %>
  <% end %>



  <div class="right menu">
    <% unless user_signed_in? %>
      <div class="item">
        <%= link_to "Регистрация", new_user_registration_path, class: 'ui secondary button' %>
      </div>
      <div class="item">
        <%= link_to "Авторизация", new_user_session_path, class: 'ui secondary button' %>
      </div>
    <% else %>
      <div class="item">
        <% if current_user.admin? %>
          <h1 class="">
            <%= image_tag('crown.png', class: 'admin-crown') %>
            <%= link_to current_user.email.split('@')[0], profile_update_path, class: 'profile-login admin-profile' %>
            <%= image_tag('crown.png', class: 'admin-crown') %>
          </h1>
        <% else %>
          <h1 class=""><%= link_to current_user.email.split('@')[0], profile_update_path, class: 'profile-login' %></h1>
        <% end %>
      </div>
      <div class="item">
        <%= link_to "Деавторизация", destroy_user_session_path, :method => :delete, class: 'ui secondary button' %>
      </div>
    <% end %>
  </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Теплоинновация</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/nav' %>
<div class="ui container p" style="padding-bottom: 100px">


  <%= render 'layouts/flash' %>

  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>